version: "3"

services:
  processor:
    build:
      context: .
      dockerfile: Dockerfile
    # network_mode: "host"

    shm_size: "2.42gb"
    env_file:
      - ../.env
      - .env
    environment:
      - LOCAL_MODE=N
      - RAY_HEAD_ADDRESS
      - RAY_DASHBOARD_PORT=8265
      - RAY_DASHBOARD_HOST=0.0.0.0
      - PRODUCER_HOST=0.0.0.0
    ports:
      - 8265:8265
      - ${AI_API_PORT}:6969
    command: uvicorn main:app --reload --port 6969 --host $PRODUCER_HOST

    # command: ["tail", "-f", "/dev/null"]
