version: "3"

services:
  processor:
    build:
      context: .
      dockerfile: Dockerfile
    # network_mode: "host"

    shm_size: "2.42gb"
    ports:
      - 8265:8265
    env_file:
      - ../.env
      - .env
    environment:
      - LOCAL_MODE=N
      - RAY_HEAD_ADDRESS
      - RAY_DASHBOARD_PORT=8265
      - RAY_DASHBOARD_HOST=0.0.0.0
    # command: ["python3", "-m", "pdb", "main.py"]
    command: ["tail", "-f", "/dev/null"]
