version: "3.6"

#===============================================
# This is a sample for extend fields
x-common-variables: &common-variables
  VARIABLE: some_value
  ANOTHER_VARIABLE: another_value

services:
  some_service:
    image: someimage
    environment: *common-variables

  another_service:
    image: anotherimage
    environment:
      <<: *common-variables
      NON_COMMON_VARIABLE: "non_common_value"
